baseURL = "https://containerd.eu/"
languageCode = "en-us"
title = "ContaiNerd"
copyright = "&copy; All lefts reversed"
theme = "hugo_theme_pickles"

[params]
  paginate = 10
  github = "tomas-mazak"
  linkedin = "tomas-mazak"
  disqus = ""
  subtitle = "Random engineer's blog"
